import './utilities/styles/reset.css'
import './utilities/styles/globals.scss'
import type { Metadata } from "next"
import { Urbanist } from "next/font/google"

const primaryfont = Urbanist({
	subsets: ["latin"],
	variable: '--font_primary'
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{
  	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={primaryfont.variable}>{children}</body>
		</html>
	)
}